apps/blog/models.py
from datetime import datetime

from apps.shared.models import db
from apps.user.models import User


# todo holds content info and how to render it
class Article(db.Model):
    __tablename__ = 'articles'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    content = db.Column(db.Text, nullable=True)
    updated_at = db.Column(db.DateTime, nullable=False)
    author_id = db.Column(db.Integer, db.ForeignKey(User.id))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class Tag(db.Model):
    __tablename__ = 'tags'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    article_id = db.Column(db.Integer, db.ForeignKey(Article.id))

apps/shared/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

apps/user/models.py
from datetime import datetime, timedelta

from flask_jwt_extended import create_access_token, create_refresh_token
from flask_security.models.fsqla import FsUserMixin, FsRoleMixin, FsModels

from apps.shared.models import db
from apps.consts import JWT_ACCESS_TOKEN_EXPIRES
from apps.utils.helpers import parse_time

FsModels.set_db_info(db, user_table_name="users", role_table_name="roles")


class Role(db.Model, FsRoleMixin):
    __tablename__ = "roles"


class User(db.Model, FsUserMixin):
    __tablename__ = 'users'
    first_name = db.Column(db.String, nullable=True)
    last_name = db.Column(db.String, nullable=True)
    updated_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    token = db.Column(db.String, index=True, unique=True)
    refresh_token = db.Column(db.String, unique=True)
    token_expiration = db.Column(db.DateTime)
    remember_me = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return f"User {self.email}"

    def to_dict(self):
        return dict(id=self.id, email=self.email)

    def get_user_tokens(self):
        now = datetime.utcnow()
        if self.token and self.token_expiration > now + timedelta(seconds=60):
            return self.token
        self.token = create_access_token(identity=self.email, fresh=True)
        self.refresh_token = create_refresh_token(identity=self.email)
        self.token_expiration = now + parse_time(JWT_ACCESS_TOKEN_EXPIRES)
        db.session.add(self)
        return self.token, self.refresh_token

    def refresh_access_token(self):
        now = datetime.utcnow()
        self.token = create_access_token(identity=self.email, fresh=False)
        self.token_expiration = now + parse_time(JWT_ACCESS_TOKEN_EXPIRES)
        db.session.add(self)
        return self.token

    def revoke_access_token(self):
        self.token_expiration = datetime.utcnow() - timedelta(seconds=1)

    @staticmethod
    def check_token(token):
        user = User.query.filter_by(token=token).first()
        if user is None or user.token_expiration < datetime.utcnow():
            return None
        return user

app.py
import os

from flask import Flask

from apps.shared.models import db
from apps.shared.app import migrate, jwt, mail
from apps.shared.routes import shared
from apps.api.routes import api
from apps.error_handlers.routes import error_handlers
from apps.auth.app import security
from apps.utils.logger import configure_logger
from apps.graphql_api.routes import graphql


def create_app():
    configure_logger()
    app = Flask(__name__)
    app.config.from_object(os.environ['APP_SETTINGS'])
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.register_blueprint(shared)
    app.register_blueprint(error_handlers)
    app.register_blueprint(api, url_prefix='/api')
    app.register_blueprint(graphql)
    db.init_app(app)
    security.init_app(app)
    jwt.init_app(app)
    mail.init_app(app)
    migrate.init_app(app, db)
    return app

apps/api/routes.py
from flask import Blueprint, request, jsonify, url_for
from flask_jwt_extended import jwt_required, current_user
from flask_security import http_auth_required

from apps.api.errors import bad_request
from apps.user.models import User
from apps.shared.models import db

api = Blueprint('api', __name__)


@api.route('/register', methods=['POST'])
def register():
    data = request.get_json() or {}
    if 'username' not in data or 'email' not in data or 'password' not in data:
        return bad_request('must include username, email and password fields')
    if User.query.filter_by(username=data['username']).first():
        return bad_request('please use a different username')
    if User.query.filter_by(email=data['email']).first():
        return bad_request('please use a different email address')
    user = User()
    user.from_dict(data, new_user=True)
    db.session.add(user)
    db.session.commit()
    response = jsonify(user.to_dict())
    response.status_code = 201
    response.headers['Location'] = url_for('api.get_user', id=user.id)
    return response


@api.route('/login', methods=['POST'])
@http_auth_required
def login():
    access_token, refresh_token = current_user().get_user_tokens()
    return jsonify(access_token=access_token, refresh_token=refresh_token)


@api.route("/refresh", methods=["POST"])
@jwt_required(refresh=True)
def refresh():
    access_token = current_user.refresh_access_token()
    return jsonify(access_token=access_token)


@api.route('/logout', methods=['DELETE'])
@jwt_required()
def revoke_token():
    current_user.revoke_access_token()
    db.session.commit()
    response = jsonify({'message': 'Logged Out'})
    response.status_code = 204
    return response


@api.route('/users/<int:user_id>', methods=['GET'])
@jwt_required()
def get_user(user_id: int):
    return jsonify(User.query.get_or_404(user_id).to_dict())

apps/blog/routes.py
from flask import Blueprint

articles = Blueprint('articles', __name__)


@articles.get("/articles/<string:title>")
def display_article(title: str):
    return f"hello {title}"

apps/error_handlers/routes.py
from flask import render_template, Blueprint, request

from apps.api.errors import error_response as api_error_response

from apps.shared.models import db

error_handlers = Blueprint('error_handlers', __name__)


def wants_json_response():
    return request.accept_mimetypes['application/json'] >= \
        request.accept_mimetypes['text/html']


@error_handlers.app_errorhandler(404)
def not_found_error(error):
    if wants_json_response():
        return api_error_response(404)
    return render_template('error_handlers/404.html'), 404


@error_handlers.app_errorhandler(405)
def not_found_error(error):
    if wants_json_response():
        return api_error_response(405)
    return render_template('error_handlers/405.html'), 405


@error_handlers.app_errorhandler(500)
def internal_error(error):
    db.session.rollback()
    if wants_json_response():
        return api_error_response(500)
    return render_template('error_handlers/500.html'), 500

apps/graphql_api/routes.py
from ariadne import make_executable_schema, graphql_sync, gql, load_schema_from_path
from ariadne.explorer import ExplorerGraphiQL
from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required

from apps.configs import Config
from apps.graphql_api.mutations import mutation
from apps.graphql_api.queries import query

graphql = Blueprint('graphql_api', __name__)
type_defs = gql(load_schema_from_path('schema.graphql'))
schema = make_executable_schema(type_defs, query, mutation)
explorer_html = ExplorerGraphiQL().html(None)


@graphql.route("/graphql", methods=["POST"])
def graphql_server():
    data = request.get_json()
    success, result = graphql_sync(
        schema,
        data,
        context_value=request,
        debug=Config.DEBUG
    )
    status_code = 200 if success else 400
    return jsonify(result), status_code


@graphql.route("/graphql", methods=["GET"])
def graphql_playground():
    return explorer_html, 200

apps/shared/app.py
from flask_jwt_extended import JWTManager
from flask_mail import Mail
from flask_migrate import Migrate


jwt = JWTManager()
migrate = Migrate()
mail = Mail()

apps/shared/routes.py
from flask import Blueprint, render_template

shared = Blueprint('shared', __name__)


@shared.route('/')
@shared.route('/index')
def index():
    return render_template('index.html', title='Soapbox')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% block styles %}{% endblock %}
</head>
<body>
<a href="{{ url_for('shared.index') }}">Home</a>
{% if current_user.is_anonymous %}
    <a href="{{ url_for('security.login') }}">Login</a>
{% else %}
    <a href="{{ url_for('security.logout') }}">Logout</a>
{% endif %}
{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
{% endblock %}
{% block footer %}
{% endblock %}
</body>
{% block scripts %}{% endblock %}
</html>

templates/error_handlers/405.html
{% extends 'base.html' %}

{% block content %}
    <title>405 Method Not Allowed</title>
    <h1>Method Not Allowed</h1>
    <p>The method is not allowed for the requested URL.</p>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    {{ super() }}
    <h1>Hello</h1>
{% endblock %}

templates/security/login_user.html
{% extends "base.html" %}

{% block content %}
    {{ super() }}
    <h1>Sign In</h1>
    <form method="POST" action="{{ url_for_security('login') }}" name="login_user_form">
        {{ login_user_form.hidden_tag() }}
        <p>
            {{ login_user_form.email.label }}<br>
            {{ login_user_form.email(size=32) }}
        </p>
        <p>
            {{ login_user_form.password.label }}<br>
            {{ login_user_form.password(size=32) }}
        </p>
        <p>{{ login_user_form.remember() }} {{ login_user_form.remember.label }}</p>
        <p>{{ login_user_form.submit() }}</p>
        <p>Forgot Your Password?
            <a href="{{ url_for('security.forgot_password') }}">Click to Reset It</a>
        </p>
        <p>New User? <a href="{{ url_for('security.register') }}">Click to Register!</a></p>
    </form>
{% endblock %}

templates/security/register_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form method="POST" action="{{ url_for_security('register') }}" name="register_user_form">
        {{ register_user_form.hidden_tag() }}
        <p>
            {{ register_user_form.username.label }}<br>
            {{ register_user_form.username(size=32) }}<br>
            {% for error in register_user_form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ register_user_form.email.label }}<br>
            {{ register_user_form.email(size=64) }}<br>
            {% for error in register_user_form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ register_user_form.password.label }}<br>
            {{ register_user_form.password(size=32) }}<br>
            {% for error in register_user_form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ register_user_form.password_confirm.label }}<br>
            {{ register_user_form.password_confirm(size=32) }}<br>
            {% for error in register_user_form.password_confirm.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ register_user_form.submit() }}</p>
    </form>
{% endblock %}